# Generated by Django 5.2.6 on 2025-10-01 11:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_model", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("overall", "Overall"),
                            ("text", "Text Generation"),
                            ("code", "Code Generation"),
                            ("creative", "Creative Writing"),
                            ("reasoning", "Reasoning"),
                            ("translation", "Translation"),
                            ("summarization", "Summarization"),
                            ("conversation", "Conversation"),
                        ],
                        max_length=100,
                    ),
                ),
                ("total_comparisons", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("ties", models.IntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("elo_rating", models.IntegerField(default=1500)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="ai_model.aimodel",
                    ),
                ),
            ],
            options={
                "db_table": "model_metrics",
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["model", "category", "-calculated_at"],
                        name="model_metri_model_i_7609dc_idx",
                    ),
                    models.Index(
                        fields=["category", "elo_rating"],
                        name="model_metri_categor_0fa4ed_idx",
                    ),
                    models.Index(
                        fields=["period", "calculated_at"],
                        name="model_metri_period_773637_idx",
                    ),
                ],
                "unique_together": {("model", "category", "period", "calculated_at")},
            },
        ),
    ]
