# Generated by Django 5.2.6 on 2025-10-01 11:45

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_model", "0001_initial"),
        ("chat_session", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "parent_message_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="Array of parent message IDs for branching conversations",
                        size=None,
                    ),
                ),
                (
                    "child_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="Array of child message IDs for easy traversal",
                        size=None,
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "participant",
                    models.CharField(
                        blank=True,
                        choices=[("a", "Model A"), ("b", "Model B")],
                        help_text="Participant identifier for compare mode",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("streaming", "Streaming"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Store tokens used, latency, model parameters, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("meta_stats_json", models.JSONField(blank=True, default=dict)),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_model.aimodel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat_session.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["session", "position"],
            },
        ),
        migrations.CreateModel(
            name="MessageRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("reply", "Reply"),
                            ("branch", "Branch"),
                            ("merge", "Merge"),
                        ],
                        default="reply",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_relations",
                        to="message.message",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_relations",
                        to="message.message",
                    ),
                ),
            ],
            options={
                "db_table": "message_relations",
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "position"], name="messages_session_966fb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["parent_message_ids"], name="messages_parent__35e5f0_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["child_ids"], name="messages_child_i_dfb68a_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["status"], name="messages_status_72d01d_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="messages_created_919c58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagerelation",
            index=models.Index(
                fields=["parent", "child"], name="message_rel_parent__bc8b4d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagerelation",
            unique_together={("parent", "child")},
        ),
    ]
