# Generated by Django 5.2.6 on 2025-10-01 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                (
                    "auth_provider",
                    models.CharField(
                        choices=[("google", "Google"), ("anonymous", "Anonymous")],
                        max_length=50,
                    ),
                ),
                (
                    "firebase_uid",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("anonymous_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("meta_stats_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                    models.Index(
                        fields=["firebase_uid"], name="users_firebas_361636_idx"
                    ),
                    models.Index(
                        fields=["is_anonymous", "anonymous_expires_at"],
                        name="users_is_anon_fb29dd_idx",
                    ),
                ],
            },
        ),
    ]
