# Generated by Django 5.2.6 on 2025-10-01 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("google", "Google"),
                            ("anthropic", "Anthropic"),
                            ("meta", "Meta"),
                            ("grok", "Grok"),
                            ("mistral", "Mistral"),
                            ("cohere", "Cohere"),
                        ],
                        max_length=100,
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("model_code", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("supports_streaming", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("meta_stats_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ai_models",
                "ordering": ["provider", "model_name"],
                "indexes": [
                    models.Index(
                        fields=["provider", "is_active"],
                        name="ai_models_provide_a6e12a_idx",
                    ),
                    models.Index(
                        fields=["model_code"], name="ai_models_model_c_122975_idx"
                    ),
                ],
            },
        ),
    ]
