# Generated by Django 5.2.6 on 2025-10-01 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_model", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Chat"),
                            ("compare", "Compare Models"),
                            ("random", "Random Models"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "share_token",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("meta_stats_json", models.JSONField(blank=True, default=dict)),
                (
                    "model_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_as_model_a",
                        to="ai_model.aimodel",
                    ),
                ),
                (
                    "model_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_as_model_b",
                        to="ai_model.aimodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "chat_sessions",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="chat_sessio_user_id_c65971_idx",
                    ),
                    models.Index(
                        fields=["share_token"], name="chat_sessio_share_t_5ae9c3_idx"
                    ),
                    models.Index(fields=["mode"], name="chat_sessio_mode_2ee3eb_idx"),
                    models.Index(
                        fields=["expires_at"], name="chat_sessio_expires_1b562e_idx"
                    ),
                ],
            },
        ),
    ]
