# Generated by Django 5.2.6 on 2025-10-01 11:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_model", "0001_initial"),
        ("chat_session", "0001_initial"),
        ("message", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("preference", "Preference"),
                            ("rating", "Rating"),
                            ("report", "Report Issue"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Categories like accuracy, helpfulness, creativity, etc.",
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="message.message",
                    ),
                ),
                (
                    "preferred_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_preferences",
                        to="ai_model.aimodel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="chat_session.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="feedback_session_5908f4_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="feedback_user_id_8e9eb5_idx",
                    ),
                    models.Index(
                        fields=["feedback_type"], name="feedback_feedbac_533c89_idx"
                    ),
                ],
            },
        ),
    ]
